### ISSUE TITLE
Compilation fails with Xcode 16.3 (apple clang 17)

### ISSUE THREAD

**Issue by fdegaulejac** [madler/zlib#1076]
I compile Zlib for iOS on Mac indirectly (included in the tensorflow-lite Conan package).
It was working with Xcode 16.1 (apple clang 16) and stopped working with Xcode 16.3 (apple clang 17).

The error is the following:
```
ERROR: /private/var/tmp/_bazel_diagnoly/6e61e86f76451756e6a898080216a464/external/zlib/BUILD.bazel:5:11: Compiling zutil.c [for tool] failed: (Exit 1): wrapped_clang failed: error executing command (from target @zlib//:zlib) external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' ... (remaining 34 arguments skipped)
In file included from external/zlib/zutil.c:8:
external/zlib/zutil.h:170:11: warning: 'OS_CODE' macro redefined [-Wmacro-redefined]
  170 | #  define OS_CODE 19
      |           ^
external/zlib/zutil.h:141:11: note: previous definition is here
  141 | #  define OS_CODE  7
      |           ^
In file included from external/zlib/zutil.c:10:
In file included from external/zlib/gzguts.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/stdio.h:61:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/_stdio.h:318:7: error: expected identifier or '('
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:16: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |                ^
```

According to https://developer.apple.com/documentation/xcode-release-notes/xcode-16_3-release-notes#Apple-Clang-Compiler

> Clang now defines TARGET_OS_* conditionals as built-in macros based on the provided target triple. This extension can be disabled with the flag -fno-define-target-os-macros. (111414452)

The root cause seems that TARGET_OS_MAC is now always defined by the compiler, and wrongly used by Zlib to check the OS (fdopen exist for iOS).

**Comment by Vollstrecker** [comment]
Seems like something is defining MACOS and APPLE. I know the cmake part doesn't define something like that, but it's hard to tell which buildsystem is used and you say conan but your snippet says bazel. So given that you use one of them there are 2 candidates that do their own thing.

Is this error replicatable when just building zlib?

**Comment by jainruchir** [comment]
Facing the same issue in a different repo (xcode 16.4)

**Comment by fdegaulejac** [comment]
The custom Conan recipe I have is using Bazel to compile Tensorflow-lite and its dependencies like Zlib.
I did not try to compile Zlib on my own, but I reproduce the issue with a simple program like this one:
```
#if defined(TARGET_OS_MAC)
NULL
#endif

int main()
{}
```
It succeeds with apple clang 16 and fails with apple clang 17 (this source purpose is only to detect a compilation error if TARGET_OS_MAC is defined).
From the documentation I saw on internet, TARGET_OS_MAC is defined for all apple os (Mac, iOS etc).

**Comment by Vollstrecker** [comment]
Nice, you've managed to show that something changed between 2 versions of apple-clang without using one of the defines that are involved within zlib.

You don't tell us what version or branch of zlib is involved, how zlib is configured or even how to reproduce the problem.

Simple question, when using current release and just build that, does the error also happen? Bonus for for current develop branch and using configure and cmake.

**Comment by Mr-Clam** [comment]
It builds fine for me with Xcode 16.4 and CMake 4.0.2, in either develop branch or v1.3.1 tag. This is my working command line:
```
cmake -S . -B _build -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=`pwd`/_install && cd build && make -j install
```
=> A problem in your environment.

**Comment by fdegaulejac** [comment]
I am using Tensorflow lite 2.15.1 so I the Zlib version would be 1.2.13 according to this: https://github.com/tensorflow/tensorflow/blob/v2.15.1/tensorflow/workspace2.bzl#L482

@Mr-Clam can you check in your cmake configuration log that you are using clang 17 provided by Xcode?

**Comment by fdegaulejac** [comment]
Ok I found something interesting!
It seems it has been fixed between 1.3 and 1.3.1:
```
git clone https://github.com/madler/zlib.git
cd zlib
git checkout v1.3 && rm -rf _build && cmake -S . -B _build && cd _build && make && cd ..
# Fails
git checkout v1.3.1 && rm -rf _build && cmake -S . -B _build && cd _build && make && cd ..
# Succeeds
```
So I guess we can this issue if that's ok with you (even if the release note does not mention anything).

**Comment by Mr-Clam** [comment]
Confirmed: it also fails for me in v1.3.  v1.3.1 and develop are good.

I have Xcode 16.4:
```
% xcodebuild -version
Xcode 16.4
Build version 16F6
% clang --version
Apple clang version 17.0.0 (clang-1700.0.13.5)
```

Or as reported by cmake config step:
```
-- The C compiler identification is AppleClang 17.0.0.17000013
```

**Comment by madler** [comment]
Thank you for the report. Fixed a year and a half ago with https://github.com/madler/zlib/commit/4bd9a71f3539b5ce47f0c67ab5e01f3196dc8ef9 . Closing.
